### ISSUE TITLE
Bonusses to special types of weapons

### ISSUE THREAD

**Issue by racerand** [ThaumRystra/DiceCloud1#169]
Like the fighting style archer adds 2 to your ranged attack bonus, it would be nice if this like all your other numbers could be tracked by DiceCloud. Right now I'm just adding 2 to the attack bonus for the weapon, but this doesn't seem in the spirit of DiceCould

**Comment by ThaumRystra** [comment]
Smarter weapons aren't planned to be implemented at all. Soon there will be custom attributes, and you will be able to create one called "rangedDamageBonus" and add it to all ranged attack rolls manually, but because attack rolls are just calculations created by the user, they are not going to be able to do anything that isn't spelled out manually.
