### ISSUE TITLE
Weapon proficiencies not implemeted

### ISSUE THREAD

**Issue by jhumphries** [ThaumRystra/DiceCloud1#178]
Maybe i'm missing something, but even though we can declare weapon proficiencies, there doesn't actually appear to be any support for them. All weapon hit calculations use the profBonus regardless of a weapon proficiency existing. 

This assumes that every weapon used will be proficient, but that isn't always the case. May be new feature to have conditional profbonus based on weapon profs by name or class. May lead to needing weapon attributes (e.g. Simple, Martial) or aliases (e.g. Longbow, Stag's Bow, Green Bow)

**Comment by ThaumRystra** [comment]
The weapon attack calculations are editable, so you can always remove the proficiency bonus if it doesn't apply, but yeah, there's been no effort to make weapon proficiencies work, mostly because weapons aren't a thing in DiceCloud, they are just items that happen to have attacks attached to them.

This is a won't-fix for now, because it requires changing some deeply rooted assumptions about items and weapons for it to get to a working stage, and even if that is done, migrating existing characters would be impossible.
