### ISSUE TITLE
Features should be able to add temporary hitpoints

### ISSUE THREAD

**Issue by ThaumRystra** [ThaumRystra/DiceCloud1#22]

**Comment by Dumbgenius** [comment]
Question: If I were to implement this, would it be better to have:

- `TemporaryHitPoints` become a child of `Feature`, or
- integrate this with #110 and make `TemporaryHitPoints` a child of `Buff`? (I personally think this is the better option here).

Either way, what do you think of implementing `TempHP` as a character `Attribute` like normal `hitPoints` (since under 5e rules you can only have temporary hit points from one source at once)?

The current TemporaryHitPoints bars would instead be used for other things that are *effectively* temporary hit points, but not actual, RAW **Temporary Hit Points** - for example an abjurer's Arcane Ward or a druid's Wild Shape.

**Comment by ThaumRystra** [comment]
I like the idea that temporary hitpoints are an attribute identical to hitpoints, and it gets its own bar that looks like the current bars, but can't be deleted, since it is based on an attribute (it gets hidden when baseValue is 0 though). Then the current hitpoint bars can go untouched, and buffs will already be able to give temporary hitpoints without changing that branch at all.
