### ISSUE TITLE
Some fields are misformatted in improved initiative export

### ISSUE THREAD

**Issue by alebahn** [ThaumRystra/DiceCloud1#96]
- Currently, the damage resistance field is an object when it is expected to be a string. It's possible that the other Vulnerabilities/Immunities fields are also wrong.
- The "InitiativeModifier" field represents a modifiers beyond the dexterity modifier. Currently, the field is getting the value from the dexterity modifier.

**Comment by ThaumRystra** [comment]
> "InitiativeModifier" field represents a modifiers beyond the dexterity modifier. Currently, the field is getting the value from the dexterity modifier.

Took a look, and [this line](https://github.com/ThaumRystra/DiceCloud1/blob/master/rpg-docs/client/views/character/export/improvedInitiativeJson.js#L29) deals with the initiave modifier: 
````
    "InitiativeModifier": skillMod("initiative"),
````

So it really should be giving the actual initiative rather than just the dexterity modifier, including effects that improve it. Do you have a test case where it isn't giving the required value?
